# Generated by Django 3.2 on 2021-04-26 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('year', models.CharField(max_length=4)),
                ('rated', models.CharField(max_length=20)),
                ('released', models.CharField(max_length=30)),
                ('runtime', models.CharField(max_length=300)),
                ('genre', models.CharField(max_length=300)),
                ('director', models.CharField(max_length=300)),
                ('writer', models.CharField(max_length=300)),
                ('actors', models.CharField(max_length=300)),
                ('plot', models.CharField(max_length=300)),
                ('language', models.CharField(max_length=300)),
                ('country', models.CharField(max_length=300)),
                ('awards', models.CharField(max_length=300)),
                ('poster', models.CharField(max_length=300)),
                ('metascore', models.CharField(max_length=300)),
                ('imdb_rating', models.CharField(max_length=300)),
                ('imdb_votes', models.CharField(max_length=300)),
                ('imdb_id', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=300)),
                ('dvd', models.CharField(max_length=300)),
                ('box_office', models.CharField(max_length=300)),
                ('production', models.CharField(max_length=300)),
                ('website', models.CharField(max_length=300)),
                ('response', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('rating_id', models.AutoField(primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=300)),
                ('value', models.CharField(max_length=300)),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.movie')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.movie')),
            ],
        ),
    ]
